import type { ImportRow, MockAdminEvent, MockOrg, MockSubmission } from "./types";

// MOCK DATA ONLY (Issue #76). Every organization, person, venue, and event
// below is fictional; contact details use reserved example domains and the
// 555-01xx phone range. Nothing is read from or written to a database.

export const MOCK_ORGS: MockOrg[] = [
  {
    id: "org-cornerstone",
    name: "Cornerstone Fellowship Nashville",
    kind: "Church",
    status: "active",
    street: "2200 Hillsboro Pike",
    city: "Nashville",
    state: "TN",
    zip: "37212",
    contactEmail: "office@example.org",
    phone: "(615) 555-0142",
    website: "https://example.org/cornerstone-nashville",
    managers: [
      { name: "Dana Whitfield", relationship: "Primary manager" },
      { name: "Marcus Bell", relationship: "Additional manager" },
    ],
    origin: "Self-registered by the church",
    lastUpdated: "2026-10-02",
  },
  {
    id: "org-harvest-gate",
    name: "Harvest Gate Ministries",
    kind: "Ministry",
    status: "active",
    street: "88 River Road",
    city: "Franklin",
    state: "TN",
    zip: "37064",
    contactEmail: "hello@example.com",
    phone: "(615) 555-0177",
    website: "https://example.org/harvest-gate",
    managers: [{ name: "Priya Anand", relationship: "Primary manager" }],
    origin: "Added by Signal One Sound staff",
    lastUpdated: "2026-09-28",
  },
  {
    id: "org-living-water",
    name: "Living Water Community Church",
    kind: "Church",
    status: "unverified",
    street: "1500 Lakeview Drive",
    city: "Murfreesboro",
    state: "TN",
    zip: "37129",
    contactEmail: "info@example.net",
    phone: "(615) 555-0113",
    website: "https://example.org/living-water",
    managers: [],
    origin: "Created from a bulk import (Fall list, batch 3)",
    lastUpdated: "2026-09-30",
  },
  {
    id: "org-firstlight",
    name: "FirstLight Youth Collective",
    kind: "Ministry",
    status: "active",
    street: "17 Maple Court",
    city: "Brentwood",
    state: "TN",
    zip: "37027",
    contactEmail: "team@example.org",
    phone: "(615) 555-0188",
    website: "https://example.org/firstlight",
    managers: [
      { name: "Jordan Pierce", relationship: "Primary manager" },
      { name: "Elena Ruiz", relationship: "Additional manager" },
      { name: "Sam Okafor", relationship: "Pending invitation" },
    ],
    origin: "Self-registered by the ministry",
    lastUpdated: "2026-10-04",
  },
  {
    id: "org-ridgeway",
    name: "Ridgeway Chapel",
    kind: "Church",
    status: "paused",
    street: "300 Ridgeway Avenue",
    city: "Hendersonville",
    state: "TN",
    zip: "37075",
    contactEmail: "contact@example.com",
    phone: "(615) 555-0129",
    website: "https://example.org/ridgeway",
    managers: [{ name: "Walter Haines", relationship: "Primary manager" }],
    origin: "Self-registered by the church",
    lastUpdated: "2026-08-19",
  },
];

export const MOCK_ADMIN_EVENTS: MockAdminEvent[] = [
  {
    id: "evt-fall-harvest",
    title: "Fall Harvest Revival",
    orgId: "org-cornerstone",
    orgName: "Cornerstone Fellowship Nashville",
    date: "2026-10-22",
    startTime: "18:30",
    venueName: "Cornerstone Main Sanctuary",
    city: "Nashville",
    state: "TN",
    revivalTypes: ["church-revival", "healing-deliverance"],
    status: "published",
    source: "church",
    sourceDetail: "Entered by Dana Whitfield",
  },
  {
    id: "evt-night-of-worship",
    title: "Night of Worship on the River",
    orgId: "org-harvest-gate",
    orgName: "Harvest Gate Ministries",
    date: "2026-10-17",
    startTime: "19:00",
    venueName: "Riverbend Pavilion",
    city: "Franklin",
    state: "TN",
    revivalTypes: ["worship-night"],
    status: "published",
    source: "admin",
    sourceDetail: "Entered by Signal One Sound staff for the ministry",
  },
  {
    id: "evt-tent-revival",
    title: "Tent Revival at the Fairgrounds",
    orgId: null,
    orgName: "Unaffiliated organizers",
    date: "2026-10-30",
    startTime: "19:00",
    venueName: "County Fairgrounds, Field B",
    city: "Lebanon",
    state: "TN",
    revivalTypes: ["tent-revival", "family"],
    status: "published",
    source: "community",
    sourceDetail: "Community submission approved 2026-10-01",
  },
  {
    id: "evt-youth-lockin",
    title: "Youth Worship Lock-in",
    orgId: "org-firstlight",
    orgName: "FirstLight Youth Collective",
    date: "2026-11-06",
    startTime: "20:00",
    venueName: "FirstLight Hall",
    city: "Brentwood",
    state: "TN",
    revivalTypes: ["youth", "worship-night"],
    status: "published",
    source: "church",
    sourceDetail: "Entered by Jordan Pierce",
  },
  {
    id: "evt-prayer-evening",
    title: "Evening of Prayer",
    orgId: "org-living-water",
    orgName: "Living Water Community Church",
    date: "2026-10-14",
    startTime: "18:00",
    venueName: "Living Water Sanctuary",
    city: "Murfreesboro",
    state: "TN",
    revivalTypes: ["prayer-gathering"],
    status: "pending-review",
    source: "import",
    sourceDetail: "Bulk import: Fall list, batch 3, row 12",
  },
  {
    id: "evt-womens-conference",
    title: "Women of Purpose Conference",
    orgId: "org-ridgeway",
    orgName: "Ridgeway Chapel",
    date: "2026-11-14",
    startTime: "09:00",
    venueName: "Ridgeway Fellowship Hall",
    city: "Hendersonville",
    state: "TN",
    revivalTypes: ["women", "conference"],
    status: "hidden",
    source: "import",
    sourceDetail: "Bulk import: Fall list, batch 2, row 4",
  },
];

export const MOCK_SUBMISSIONS: MockSubmission[] = [
  {
    id: "sub-bridge-baptism",
    title: "Community Baptism at Cedar Creek",
    submittedBy: "Anonymous community member",
    submitterNote: "No account; submitted from a public form (illustrative)",
    submittedOn: "2026-10-04",
    date: "2026-10-18",
    startTime: "14:00",
    venueName: "Cedar Creek Park Pavilion",
    city: "Mt. Juliet",
    state: "TN",
    revivalTypes: ["baptism"],
    flags: ["Venue not matched to a known organization", "No website or contact provided"],
  },
  {
    id: "sub-fall-harvest-dup",
    title: "Fall Harvest Revival (Cornerstone)",
    submittedBy: "Jamie Torres",
    submitterNote: "Signed-in member, 3 prior approved submissions (illustrative)",
    submittedOn: "2026-10-05",
    date: "2026-10-22",
    startTime: "18:30",
    venueName: "Cornerstone Main Sanctuary",
    city: "Nashville",
    state: "TN",
    revivalTypes: ["church-revival"],
    flags: ["Matches an existing published event"],
    possibleDuplicateOf: "evt-fall-harvest",
  },
  {
    id: "sub-mens-breakfast",
    title: "Men's Prayer Breakfast",
    submittedBy: "Chris Delgado",
    submitterNote: "Signed-in member, first submission (illustrative)",
    submittedOn: "2026-10-05",
    date: "2026-10-24",
    startTime: "07:30",
    venueName: "Grace Hall",
    city: "Gallatin",
    state: "TN",
    revivalTypes: ["men", "prayer-gathering"],
    flags: ["First-time submitter"],
  },
  {
    id: "sub-unclear-gathering",
    title: "BIG NIGHT!!! Everybody Come!!!",
    submittedBy: "Anonymous community member",
    submitterNote: "No account; submitted from a public form (illustrative)",
    submittedOn: "2026-10-06",
    date: "2026-10-12",
    startTime: "19:00",
    venueName: "",
    city: "Nashville",
    state: "TN",
    revivalTypes: ["other"],
    flags: ["Missing venue", "Title may not describe the event", "Revival Type is Other"],
  },
];

export const IMPORT_FILE_NAME = "fall-gatherings-sample.csv";

const row = (
  line: number,
  organization: string,
  eventTitle: string,
  date: string,
  startTime: string,
  venue: string,
  city: string,
  zip: string,
): ImportRow => ({ line, organization, eventTitle, date, startTime, venue, city, state: "TN", zip });

/** Fictional rows deliberately containing valid, invalid, duplicate, and conflicting cases. */
export const IMPORT_ROWS: ImportRow[] = [
  row(2, "Harvest Gate Ministries", "Prayer & Fasting Weekend", "2026-11-07", "18:00", "Harvest Gate Hall", "Franklin", "37064"),
  row(3, "Living Water Community Church", "Evening of Prayer", "2026-10-14", "18:00", "Living Water Sanctuary", "Murfreesboro", "37129"),
  row(4, "Cornerstone Fellowship Nashville", "Fall Harvest Revival", "2026-10-22", "19:00", "Cornerstone Main Sanctuary", "Nashville", "37212"),
  row(5, "Hope Springs Church", "Family Worship Night", "2026-13-05", "18:30", "Hope Springs Chapel", "Lebanon", "37087"),
  row(6, "", "Revival Weekend", "2026-11-20", "19:00", "Old Mill Church", "Lebanon", "37087"),
  row(7, "Hope Springs Church", "Family Worship Night", "2026-11-05", "6:30pm", "Hope Springs Chapel", "Lebanon", "37087"),
  row(8, "Pine Hill Chapel", "Healing Service", "2026-11-12", "19:00", "Pine Hill Chapel", "Gallatin", "372"),
  row(9, "Harvest Gate Ministries", "Prayer & Fasting Weekend", "2026-11-07", "18:00", "Harvest Gate Hall", "Franklin", "37064"),
];
